"""Init

Revision ID: 7e5a4a947fa1
Revises: 9bbc128c2927
Create Date: 2024-04-16 14:13:36.474554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7e5a4a947fa1'
down_revision: Union[str, None] = '9bbc128c2927'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('crated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('refresh_token', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.add_column('contacts', sa.Column('crated_at', sa.DateTime(), nullable=True))
    op.add_column('contacts', sa.Column('user_id', sa.Integer(), nullable=True))
    op.alter_column('contacts', 'first_name',
               existing_type=sa.VARCHAR(length=25),
               type_=sa.String(length=50),
               nullable=False)
    op.alter_column('contacts', 'last_name',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('contacts', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('contacts', 'phone_number',
               existing_type=sa.VARCHAR(length=25),
               type_=sa.String(length=15),
               nullable=False)
    op.alter_column('contacts', 'born_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('contacts', 'description',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=150),
               existing_nullable=True)
    op.drop_index('ix_contacts_id', table_name='contacts')
    op.drop_index('ix_contacts_last_name', table_name='contacts')
    op.create_unique_constraint(None, 'contacts', ['phone_number'])
    op.create_foreign_key(None, 'contacts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('contacts', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'contacts', type_='foreignkey')
    op.drop_constraint(None, 'contacts', type_='unique')
    op.create_index('ix_contacts_last_name', 'contacts', ['last_name'], unique=False)
    op.create_index('ix_contacts_id', 'contacts', ['id'], unique=False)
    op.alter_column('contacts', 'description',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=250),
               existing_nullable=True)
    op.alter_column('contacts', 'born_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('contacts', 'phone_number',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=25),
               nullable=True)
    op.alter_column('contacts', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('contacts', 'last_name',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.alter_column('contacts', 'first_name',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=25),
               nullable=True)
    op.drop_column('contacts', 'user_id')
    op.drop_column('contacts', 'crated_at')
    op.drop_table('users')
    # ### end Alembic commands ###
